### ISSUE TITLE
Missing Start Menu shortcuts

### ISSUE THREAD

**Issue by KOOKIIEStudios** [BAA-Studios/SunnyFORM#2]
## Abstract
I already have portable builds of CastFORM on my system, so when i was doing testing, Windows showed that when i searched the Start menu. I had erroneously thought that this meant WiX added a shortcut automatically.

# Tasks
- [x] ~~Add components-wrapped `Directory` objects to `Folder.wxs` for start menu directory structure~~ Not required since we're using a `BAA Studios` folder for it - switched to using standard directory variable
- [x] ~~Add `ComponentGroup` to `AppComponents.wxs` for shortcut components~~ Not required any more, since it's now piggyback on the application entry point
- [x] ~~Add component-wrapped `File` object to component group~~ Not required any more, since it's now piggyback on the application entry point
- [x] Check to see if manual input of registry key is still required for WiX v4 - update: not required if shortcut advertisement is allowed
- [x] ~~Add component group to `Package.wxs`~~ Not required any more, since it's now piggyback on the application entry point

**Comment by KOOKIIEStudios** [comment]
Completed as of 4be3e6e
